Povoamento da Dimensão Campanha

In [20]:
import pandas as pd

Carregar dados da fonte

In [21]:
campanhas = pd.read_csv('../Fontes/campanhas.csv', encoding='latin1')
print(f"Registos de campanhas lidos: {campanhas.shape[0]}")
campanhas.head()

Registos de campanhas lidos: 7

,id_campanha,nome,tipo,data_inicio,data_fim,descricao,publico_alvo
0,C001,Campanha de Boas-Vindas,Aquisição,1/1/2025,12/31/2025,Acesso gratuito à EasyFit durante a primeira ...,Novos clientes
1,C002,Desafio 3 Semanas de Circuitos,Fidelização,1/1/2025,12/31/2025,Incentivo à frequência regular com o objetivo...,Clientes ativos
2,C003,Circuito Experiência,Personalização,1/1/2025,12/31/2025,Promoção de experimentação de novos circuitos ...,Clientes regulares
3,C004,Leva um Amigo,Aquisição,1/1/2025,12/31/2025,Clientes podem trazer um amigo gratuitamente d...,Todos os clientes
4,C005,Desconto por Frequência,Fidelização,1/1/2025,12/31/2025,Oferece desconto na mensalidade se o cliente c...,Clientes ativos

Verificação de Integridade

In [22]:
# Verificar valores nulos
print("Valores em falta:")
print(campanhas.isnull().sum())

# Verificar duplicados com base na chave natural (ID)
print("\nDuplicados com base no ID:")
print(campanhas.duplicated(subset=["id_campanha"]).sum())

Valores em falta:
id_campanha     0
nome            0
tipo            0
data_inicio     0
data_fim        0
descricao       0
publico_alvo    0
dtype: int64

Duplicados com base no ID:
0

Seleção dos Atributos

In [23]:
dim_campanha = campanhas[[
    'id_campanha', 'nome', 'tipo', 'data_inicio',
    'data_fim', 'descricao', 'publico_alvo'
]].copy()

dim_campanha = dim_campanha.rename(columns={
    'id_campanha': 'campanha_id',
    'nome': 'campanha_nome',
    'tipo': 'campanha_tipo',
    'data_inicio': 'campanha_data_inicio', 
    'data_fim': 'campanha_data_fim',
    'descricao': 'campanha_descricao',
    'publico_alvo': 'campanha_publico_alvo'
})

Gerar Surrogate Key

In [24]:
dim_campanha.insert(1, 'campanha_sk', range(1, 1 + len(dim_campanha)))

Exportação dos Dados

In [25]:
dim_campanha.to_csv("../Dados Finais/dim_campanha.csv", index=False, encoding="utf-8-sig")
print("Dimensão Campanha pronta para carga!")
dim_campanha.head()

Dimensão Campanha pronta para carga!

,campanha_id,campanha_sk,campanha_nome,campanha_tipo,campanha_data_inicio,campanha_data_fim,campanha_descricao,campanha_publico_alvo
0,C001,1,Campanha de Boas-Vindas,Aquisição,1/1/2025,12/31/2025,Acesso gratuito à EasyFit durante a primeira ...,Novos clientes
1,C002,2,Desafio 3 Semanas de Circuitos,Fidelização,1/1/2025,12/31/2025,Incentivo à frequência regular com o objetivo...,Clientes ativos
2,C003,3,Circuito Experiência,Personalização,1/1/2025,12/31/2025,Promoção de experimentação de novos circuitos ...,Clientes regulares
3,C004,4,Leva um Amigo,Aquisição,1/1/2025,12/31/2025,Clientes podem trazer um amigo gratuitamente d...,Todos os clientes
4,C005,5,Desconto por Frequência,Fidelização,1/1/2025,12/31/2025,Oferece desconto na mensalidade se o cliente c...,Clientes ativos